<x-filament-panels::page>
    <form wire:submit="saveCustomer" class="space-y-5 pb-8">
        <div class="bg-white rounded-2xl shadow-sm p-5 space-y-4">
            <h2 class="font-extrabold">Customer Information</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div class="md:col-span-2"><label class="fi-fo-field-wrp-label">{{ match($this->profileType()) { 'fleet' => 'Fleet Account Name', 'oe' => 'OE Account Name', 'ib' => 'IB Account Name', default => 'Store Name' } }} *</label><x-filament::input wire:model="name" />@error('name')<p class="text-danger-600 text-sm">{{ $message }}</p>@enderror</div>
                <div><label class="fi-fo-field-wrp-label">Customer Code</label><x-filament::input wire:model="unique_id" /></div>
                <div><label class="fi-fo-field-wrp-label">Company *</label><select wire:model.live="company_id" class="fi-input w-full"><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></div>
                <div><label class="fi-fo-field-wrp-label">General Category</label><select wire:model="general_category_id" class="fi-input w-full"><option value="">Select category</option>@foreach($generalCategories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>
                @if((int) $general_category_id === 1)<div><label class="fi-fo-field-wrp-label">Competitor Volume</label><select wire:model="competitor_volume" class="fi-input w-full"><option value="">Not specified</option><option value="1">High</option><option value="2">Medium</option><option value="3">Low</option></select></div>@endif
                <div><label class="fi-fo-field-wrp-label">Access</label><select wire:model="access_user_ids" multiple class="fi-input w-full h-24">@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div>
                @if($this->profileType() === 'outlet')<div><label class="fi-fo-field-wrp-label">Person in Charge</label><select wire:model="person_in_charge_id" class="fi-input w-full"><option value="">Select person</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div>@endif
                <div class="md:col-span-3"><label class="fi-fo-field-wrp-label">Address</label><textarea wire:model="address" class="fi-input w-full" rows="3"></textarea></div>
                <div><label class="fi-fo-field-wrp-label">Contact Person</label><x-filament::input wire:model="contact_person" /></div>
                <div><label class="fi-fo-field-wrp-label">Business Landline Number</label><x-filament::input wire:model="business_landline_number" /></div>
                <div><label class="fi-fo-field-wrp-label">Business Mobile Number</label><x-filament::input wire:model="business_mobile_number" /></div>
                <div><label class="fi-fo-field-wrp-label">Date Established</label><x-filament::input type="date" wire:model="date_established" /></div>
                <div class="flex items-center gap-2"><input type="checkbox" wire:model="is_active" class="rounded"><label>Active</label></div>
            </div>
        </div>

        <div class="bg-white rounded-2xl shadow-sm p-5 space-y-4">
            <h2 class="font-extrabold">Location</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div><label class="fi-fo-field-wrp-label">Region</label><select wire:model.live="physical_region_id" class="fi-input w-full"><option value="">Select region</option>@foreach($regions as $region)<option value="{{ $region->id }}">{{ $region->name }}</option>@endforeach</select></div>
                <div><label class="fi-fo-field-wrp-label">Specific Region</label><select wire:model="region_specific_id" class="fi-input w-full"><option value="">Select specific region</option>@foreach($regionSpecifics as $region)<option value="{{ $region->id }}">{{ $region->name }}</option>@endforeach</select></div>
                <div><label class="fi-fo-field-wrp-label">Province</label><select wire:model.live="province_id" class="fi-input w-full"><option value="">No province / independent locality</option>@foreach($provinces->where('region_id', $physical_region_id) as $province)<option value="{{ $province->id }}">{{ $province->name }}</option>@endforeach</select></div>
                <div><label class="fi-fo-field-wrp-label">City / Municipality</label><select wire:model="municipality_id" class="fi-input w-full"><option value="">Select municipality</option>@foreach($municipalities->where('region_id', $physical_region_id)->where('province_id', $province_id) as $municipality)<option value="{{ $municipality->id }}">{{ $municipality->name }}</option>@endforeach</select></div>
                <div><label class="fi-fo-field-wrp-label">Latitude</label><x-filament::input type="number" step="any" wire:model="latitude" /></div>
                <div><label class="fi-fo-field-wrp-label">Longitude</label><x-filament::input type="number" step="any" wire:model="longitude" /></div>
                <div><label class="fi-fo-field-wrp-label">Barangay</label><x-filament::input disabled placeholder="Unavailable" /></div>
                <div><label class="fi-fo-field-wrp-label">Area Cluster</label><x-filament::input disabled placeholder="Unavailable" /></div>
            </div>
        </div>

        @php($profile = $this->profileType())
        <div class="bg-white rounded-2xl shadow-sm p-5 space-y-4">
            <h2 class="font-extrabold">{{ ucfirst($profile ?: 'Customer') }} Profile</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                @if($profile === 'outlet' || $profile === 'oe')<div><label class="fi-fo-field-wrp-label">Entry Detail</label><select wire:model.live="trade.entry_detail" class="fi-input w-full"><option value="">Select entry detail</option>@foreach(config("customer_trade_form.profile_entry_details.{$profile}", []) as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select></div>@endif
                @if($profile === 'outlet')
                    <div class="md:col-span-2"><label class="fi-fo-field-wrp-label">Classifications</label><select wire:model="trade.classifications" multiple class="fi-input w-full h-24">@foreach(config('customer_trade_form.profile_classifications.outlet', []) as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select></div>
                    <div class="md:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-4"><div><label class="fi-fo-field-wrp-label">Conversion Program</label><x-filament::input wire:model="active.conversion_program" /></div><div><label class="fi-fo-field-wrp-label">Working Days</label><select wire:model="trade.working_days" multiple class="fi-input w-full h-24">@foreach(config('customer_trade_form.working_days', []) as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select></div><div><label class="fi-fo-field-wrp-label">ULAB</label><select wire:model="active.ulab" class="fi-input w-full"><option value="">Select</option><option value="GRC">GRC</option><option value="Consolidator">Consolidator</option><option value="None">None</option></select></div><div><label class="fi-fo-field-wrp-label">Opening Time</label><x-filament::input type="time" wire:model="active.operating_hours.start" /></div><div><label class="fi-fo-field-wrp-label">Closing Time</label><x-filament::input type="time" wire:model="active.operating_hours.end" /></div><div class="flex items-center gap-2 pt-6"><input type="checkbox" wire:model.live="trade.motiv_user" class="rounded"><label>MOTIV User</label></div>@if($trade['motiv_user'] ?? false)<div><label class="fi-fo-field-wrp-label">Warehouse Code</label><x-filament::input wire:model="active.warehouse_code" /></div>@endif<div><label class="fi-fo-field-wrp-label">Delivery Type</label><select wire:model.live="active.delivery_type" class="fi-input w-full"><option value="">Select</option><option value="yes">Yes</option><option value="no">No</option></select></div>@if(($active['delivery_type'] ?? null) === 'yes')<div><label class="fi-fo-field-wrp-label">Delivery Detail</label><select wire:model="active.delivery_detail" class="fi-input w-full"><option value="">Select</option><option value="own_delivery">Own Delivery</option><option value="meh">MEH</option></select></div>@endif</div>
                @elseif($profile === 'fleet')
                    <div><label class="fi-fo-field-wrp-label">Type</label><select wire:model="active.account_type" class="fi-input w-full"><option value="">Select</option><option value="newly_mapped">Newly Mapped</option><option value="existing">Existing</option></select></div><div><label class="fi-fo-field-wrp-label">Classification</label><select wire:model="active.classifications" class="fi-input w-full"><option value="">Select</option>@foreach(config('customer_trade_form.profile_classifications.fleet', []) as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select></div><div><label class="fi-fo-field-wrp-label">Battery Class</label><select wire:model="active.battery_class" class="fi-input w-full"><option value="">Select</option><option value="maintenance_free">Maintenance Free</option><option value="low_maintenance">Low Maintenance</option></select></div><div><label class="fi-fo-field-wrp-label">Status</label><select wire:model="active.status" class="fi-input w-full"><option value="">Select</option><option value="active">Active</option><option value="dormant">Dormant</option><option value="irregular">Irregular</option></select></div>
                @elseif($profile === 'oe')<div><label class="fi-fo-field-wrp-label">Classification</label><select wire:model="active.classifications" class="fi-input w-full"><option value="">Select</option>@foreach(config('customer_trade_form.profile_classifications.oe', []) as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select></div><div><label class="fi-fo-field-wrp-label">Battery Class</label><select wire:model="active.battery_class" class="fi-input w-full"><option value="">Select</option><option value="maintenance_free">Maintenance Free</option><option value="low_maintenance">Low Maintenance</option></select></div>@if(($trade['entry_detail'] ?? null) === 'Acid')<div class="flex items-center gap-2 pt-6"><input type="checkbox" wire:model="active.sulfuric_acid" class="rounded"><label>Sulfuric Acid</label></div>@endif
                @elseif($profile === 'ib')<div><label class="fi-fo-field-wrp-label">Classification</label><select wire:model="active.classifications" class="fi-input w-full"><option value="">Select</option>@foreach(config('customer_trade_form.profile_classifications.ib', []) as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select></div>
                @endif
            </div>
        </div>

        @if($profile) @foreach(config("customer_trade_form.category_streams.{$profile}.streams", []) as $stream) @if($profile !== 'outlet' || ($trade['entry_detail'] ?? null) === 'AB and MCB' || ($stream === 'ab' && ($trade['entry_detail'] ?? null) === 'AB') || ($stream === 'mcb' && ($trade['entry_detail'] ?? null) === 'MCB'))
            <div class="bg-white rounded-2xl shadow-sm p-5 space-y-3"><h2 class="font-extrabold">{{ strtoupper($stream) }} Annual Categories</h2><div class="grid grid-cols-1 md:grid-cols-3 gap-3">@foreach($categories[$stream] ?? [] as $year => $category)<div><label class="fi-fo-field-wrp-label">{{ $year }}</label><select wire:model="categories.{{ $stream }}.{{ $year }}" class="fi-input w-full"><option value="">Select category</option>@foreach($this->categoryOptions($stream) as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>@endforeach</div></div>
        @endif @endforeach @endif

        <div class="bg-white rounded-2xl shadow-sm p-5 space-y-3"><h2 class="font-extrabold">Owner Profile</h2><div class="grid grid-cols-1 md:grid-cols-3 gap-4">@foreach(['name' => 'Name of Owner', 'birthday' => 'Birthday', 'nickname' => 'Nickname', 'successor_name' => 'Successor Name', 'successor_birthday' => 'Successor Birthday', 'relationship' => 'Relationship with the Owner', 'generation' => 'Generation', 'hobbies' => 'Hobbies'] as $key => $label)<div class="{{ $key === 'hobbies' ? 'md:col-span-2' : '' }}"><label class="fi-fo-field-wrp-label">{{ $label }}</label>@if(str_contains($key, 'birthday'))<x-filament::input type="date" wire:model="active.owner.{{ $key }}" />@elseif($key === 'hobbies')<textarea wire:model="active.owner.{{ $key }}" class="fi-input w-full"></textarea>@else<x-filament::input wire:model="active.owner.{{ $key }}" />@endif</div>@endforeach</div></div>

        @error('categories')<p class="text-danger-600">{{ $message }}</p>@enderror @error('active.*')<p class="text-danger-600">{{ $message }}</p>@enderror @error('access_user_ids')<p class="text-danger-600">{{ $message }}</p>@enderror @error('person_in_charge_id')<p class="text-danger-600">{{ $message }}</p>@enderror @error('trade')<p class="text-danger-600">{{ $message }}</p>@enderror @error('physical_region_id')<p class="text-danger-600">{{ $message }}</p>@enderror @error('province_id')<p class="text-danger-600">{{ $message }}</p>@enderror @error('municipality_id')<p class="text-danger-600">{{ $message }}</p>@enderror
        <div class="flex justify-end gap-3"><a href="{{ \App\Filament\Pages\CustomerPage::getUrl() }}" class="fi-btn">Cancel</a><button type="submit" class="fi-btn fi-color-primary">Save Customer</button></div>
    </form>
</x-filament-panels::page>
